export const cardDeck = [
  { cardType: "explode", text: "Goodbye cruel world" , id: 1},
  { cardType: "explode", text: "It's the dawn of the cat age" , id: 2},
  { cardType: "explode", text: "Who gave the cat a grenade?", id: 3 },
  { cardType: "explode", text: "I knew cats were evil", id: 4 },
  { cardType: "defuse", text: "whew, that was a close one", id: 5 },
  { cardType: "defuse", text: "I'm still alive suckers!", id: 6 },
  { cardType: "defuse", text: "Missed a spot", id: 7 },
  { cardType: "defuse", text: "Saved by the defuse card", id: 8 },
  { cardType: "defuse", text: "I have found salvation", id: 9 },
  { cardType: "defuse", text: "I might just stay alive", id: 10 },
  { cardType: "favor", text: "Gives me a card please", id: 11 },
  { cardType: "favor", text: "I ask nicely for a card", id: 12 },
  { cardType: "favor", text: "yay a free card", id: 13 },
  { cardType: "favor", text: "please give me a good card", id: 14 },
  { cardType: "skip", text: "I choose skip!", id: 15 },
  { cardType: "skip", text: "I'm going to skip this one out", id: 16 },
  { cardType: "skip", text: "Skipping away...", id: 17 },
  { cardType: "skip", text: "Skipping out of demise", id: 18 },
  { cardType: "attack", text: "Hope you die", id: 19 },
  { cardType: "attack", text: "Attack I choose you!", id: 20 },
  { cardType: "attack", text: "Enjoy these attacks", id: 21 },
  { cardType: "attack", text: "I love attacking others", id: 22 },
  { cardType: "future", text: "I am god", id: 23 },
  { cardType: "future", text: "where's my magic 8 ball", id: 24 },
  { cardType: "future", text: "I feel a shift in my destiny", id: 25 },
  { cardType: "future", text: "enhancing my calm", id: 26 },
  { cardType: "future", text: "let's see what will happen", id: 27 },
  { cardType: "nope", text: "No, No, Nope", id: 28 },
  { cardType: "nope", text: "Nope sandwich", id: 29 },
  { cardType: "nope", text: "Neighh!!", id: 30 },
  { cardType: "nope", text: "winning the nopebell peace prize", id: 31 },
  { cardType: "nope", text: "I am a nope ninja", id: 32 },
  { cardType: "shuffle", text: "everyday I'm shuffling", id: 33 },
  { cardType: "shuffle", text: "may the odds ever be in my favor", id: 34 },
  { cardType: "shuffle", text: "deck.shuffle()", id: 35 },
  { cardType: "shuffle", text: "shuffle like your life depends on it", id: 36 },
  { cardType: "combo1", text: "HRNNGGG!", id: 37 },
  { cardType: "combo1", text: "HRNNGGG!", id: 38 },
  { cardType: "combo1", text: "HRNNGGG!", id: 39 },
  { cardType: "combo1", text: "HRNNGGG!", id: 40 },
  { cardType: "combo2", text: "Tacocat - I am a palindrome", id: 41 },
  { cardType: "combo2", text: "Tacocat -I am a palindrome", id: 42 },
  { cardType: "combo2", text: "Tacocat - I am a palindrome", id: 43 },
  { cardType: "combo2", text: "Tacocat -I am a palindrome", id: 44 },
  { cardType: "combo3", text: "Beardcats are awesome", id: 45 },
  { cardType: "combo3", text: "Beardcats are awesome", id: 46 },
  { cardType: "combo3", text: "Beardcats are awesome", id: 47 },
  { cardType: "combo3", text: "Beardcats are awesome", id: 48 },
  { cardType: "combo4", text: "part cat part potato", id: 49 },
  { cardType: "combo4", text: "part cat part potato", id: 50 },
  { cardType: "combo4", text: "part cat part potato", id: 51 },
  { cardType: "combo4", text: "part cat part potato", id: 52 },
  { cardType: "combo5", text: "care for a cattermelon?", id: 53 },
  { cardType: "combo5", text: "care for a cattermelon?", id: 54 },
  { cardType: "combo5", text: "care for a cattermelon?", id: 55 },
  { cardType: "combo5", text: "care for a cattermelon?", id: 56 },
]
